import { Ally, ContainerItem } from './Types';

// Default Chemical Allies (Keeping existing allies)
export const DEFAULT_ALLIES: Ally[] = [
  {
    id: 'firestarter',
    name: 'The Firestarter',
    face: '⚙️',
    invocation: 'May this flame light what matters, not what merely demands.',
    function: 'Ignites focus, momentum, motion — reminds the nervous system of possibility.',
    shadow: 'Mistakes speed for progress; burns through rest, not toward it.',
    ritual: 'Before dosing — place one hand on your chest, feel the heartbeat you\'re about to quicken. Whisper: "Burn bright, not away."',
    log: [],
  },
  {
    id: 'mirror',
    name: 'The Mirror and the Mystery',
    face: '🌌',
    invocation: 'Show me myself as cosmos, but bring me back whole.',
    function: 'Expands the membrane between self and all — reveals the divine recursion in experience.',
    shadow: 'Reveals too much too fast — replaces integration with revelation.',
    ritual: 'Before the threshold, speak one truth you\'re willing to lose and one you wish to keep.',
    log: [],
  },
  {
    id: 'chalice',
    name: 'The Hollow Chalice',
    face: '🍷',
    invocation: 'Let this cup open warmth, not emptiness.',
    function: 'Loosens the social heart, dissolves distance, invites song.',
    shadow: 'Hollows the self in the name of connection.',
    ritual: 'Touch your glass to your lips, then pause — breathe once before the sip. Ask: "Am I joining, or escaping?"',
    log: [],
  },
  {
    id: 'tinkerer',
    name: 'The Tinkerer',
    face: '💨',
    invocation: 'Let curiosity spark, not spiral.',
    function: 'Sharpens attention, traces detail, ritualizes pause.',
    shadow: 'Turns precision into obsession; mistake control for safety.',
    ritual: 'Exhale deliberately. Watch the smoke/diffusion fade and whisper: "Release what I tried to fix."',
    log: [],
  },
  {
    id: 'entropy',
    name: 'Entropy\'s Embrace',
    face: '⚫',
    invocation: 'Hold me until I can hold myself.',
    function: 'Teaches surrender, relief, and the grace of rest.',
    shadow: 'Makes oblivion seductive; trades awareness for absence.',
    ritual: 'Before contact — press a hand into the earth, bed, or floor. Feel gravity\'s embrace and say: "May I return."',
    log: [],
  },
  {
    id: 'godmother',
    name: 'The Green Godmother',
    face: '🍃',
    invocation: 'Let me see the pattern without losing form.',
    function: 'Bridges sensory and symbolic worlds — a translator between logic and intuition.',
    shadow: 'Turns awe into apathy; mists clarity under the guise of peace.',
    ritual: 'After inhaling, touch something textured — leaf, fabric, wall — whisper: "Anchor the wonder."',
    log: [],
  },
  {
    id: 'silence',
    name: 'The Mother of Silence',
    face: '🌊',
    invocation: 'Teach me calm that still remembers.',
    function: 'Soothes storms, restores coherence, holds panic like a child.',
    shadow: 'Quiet becomes erasure; calm becomes dependence.',
    ritual: 'After dosing, listen for the quietest sound in your environment — say softly: "I remain."',
    log: [],
  },
  {
    id: 'architect',
    name: 'The Architect',
    face: '🧠',
    invocation: 'May structure serve spirit.',
    function: 'Refines clarity, strengthens connection, rebuilds cognitive architecture.',
    shadow: 'Seeks perfection where presence would suffice.',
    ritual: 'Before swallowing, tap the capsule or cup three times and say: "Alive design, not rigid design."',
    log: [],
  },
];

// Default Grounding Anchors (Expanded to include all items from the provided documents)
export const DEFAULT_GROUNDING_ITEMS: ContainerItem[] = [
  // --- Time-based anchors ---
  // Morning (Theme: orient gently; don’t command yourself awake.)
  {
    id: 'morning-light',
    title: 'Light check-in',
    body_cue: 'notice the quality of light, warm or cool, bright or dim',
    micro: 'lift your eyes toward it',
    container: 'morning',
    category: 'time',
    desire: '',
  },
  {
    id: 'morning-body',
    title: 'Body arrival',
    body_cue: 'sense where weight meets ground; let breath lengthen',
    micro: 'feel your feet',
    container: 'morning',
    category: 'time',
    desire: '',
  },
  {
    id: 'morning-gratitude',
    title: 'First gratitude',
    body_cue: 'name one thing that feels okay or steady',
    micro: 'whisper “thank you” once',
    container: 'morning',
    category: 'time',
    desire: '',
  },
  {
    id: 'morning-breath',
    title: 'Slow breath',
    body_cue: 'three slow inhales through the nose, exhale through the mouth',
    micro: 'one conscious breath',
    container: 'morning',
    category: 'time',
    desire: '',
  },

  // Afternoon (Theme: release built-up charge, re-enter presence.)
  {
    id: 'afternoon-hydration',
    title: 'Hydration reset',
    body_cue: 'taste water, feel temperature, notice the act of swallowing',
    micro: 'one sip with attention',
    container: 'afternoon',
    category: 'time',
    desire: '',
  },
  {
    id: 'afternoon-muscle',
    title: 'Muscle check',
    body_cue: 'unclench jaw, roll shoulders, exhale tension',
    micro: 'drop shoulders once',
    container: 'afternoon',
    category: 'time',
    desire: '',
  },
  {
    id: 'afternoon-horizon',
    title: 'Horizon view',
    body_cue: 'look at something distant for ten seconds',
    micro: 'glance toward open space',
    container: 'afternoon',
    category: 'time',
    desire: '',
  },
  {
    id: 'afternoon-truth',
    title: 'Truth check',
    body_cue: 'ask silently, “what’s actually true right now?”',
    micro: 'one honest exhale',
    container: 'afternoon',
    category: 'time',
    desire: '',
  },

  // Evening (Theme: unwind; let cognition return to body.)
  {
    id: 'evening-lighting',
    title: 'Lighting shift',
    body_cue: 'dim screens and lamps; let light grow warmer',
    micro: 'lower one light',
    container: 'evening',
    category: 'time',
    desire: '',
  },
  {
    id: 'evening-water',
    title: 'Water ritual',
    body_cue: 'wash or rinse hands slowly, noticing temperature and feel',
    micro: 'wet palms briefly',
    container: 'evening',
    category: 'time',
    desire: '',
  },
  {
    id: 'evening-gratitude',
    title: 'Gratitude exhale',
    body_cue: 'inhale what you want to keep; exhale what can leave',
    micro: 'one gentle sigh',
    container: 'evening',
    category: 'time',
    desire: '',
  },
  {
    id: 'evening-scan',
    title: 'Body scan mini',
    body_cue: 'notice one tense area, breathe into it',
    micro: 'name one body part',
    container: 'evening',
    category: 'time',
    desire: '',
  },

  // Late (Theme: signal safety; prepare for rest without force.)
  {
    id: 'late-breath',
    title: 'Slow breathing',
    body_cue: 'inhale four, hold two, exhale six',
    micro: 'one slow breath',
    container: 'late',
    category: 'time',
    desire: '',
  },
  {
    id: 'late-nest',
    title: 'Nest ritual',
    body_cue: 'adjust blanket or pillow; whisper “safe now.”',
    micro: 'smooth pillow once',
    container: 'late',
    category: 'time',
    desire: '',
  },
  {
    id: 'late-checkin',
    title: 'Quiet check-in',
    body_cue: 'ask, “is there anything left that needs attention?” then rest',
    micro: 'let the thought pass',
    container: 'late',
    category: 'time',
    desire: '',
  },
  {
    id: 'late-muscle',
    title: 'Muscle melt',
    body_cue: 'tense all muscles for five seconds, then release',
    micro: 'soften face',
    container: 'late',
    category: 'time',
    desire: '',
  },

  // --- Situational Grounding (Category: situational) ---
  // Overstimulated (Theme: cool the system, return to containment.)
  {
    id: 'sit-over-temp',
    title: 'Temperature anchor',
    body_cue: 'run cool water over wrists or neck until breath slows',
    micro: 'touch cool surface',
    container: 'situational',
    category: 'situational',
    desire: '',
  },
  {
    id: 'sit-over-boundary',
    title: 'Boundary anchor',
    body_cue: 'lean against a wall; feel your edges',
    micro: 'press one shoulder to wall',
    container: 'situational',
    category: 'situational',
    desire: '',
  },
  {
    id: 'sit-over-sound',
    title: 'Sound anchor',
    body_cue: 'find quiet hum or steady tone; breathe with it',
    micro: 'notice silence between sounds',
    container: 'situational',
    category: 'situational',
    desire: '',
  },
  {
    id: 'sit-over-visual',
    title: 'Visual anchor',
    body_cue: 'lower gaze, soften focus, let blur happen',
    micro: 'close eyes halfway',
    container: 'situational',
    category: 'situational',
    desire: '',
  },

  // Under-motivated (Theme: coax motion without pressure.)
  {
    id: 'sit-under-activation',
    title: 'Small activation',
    body_cue: 'move one body part with curiosity',
    micro: 'flex toes or fingers',
    container: 'situational',
    category: 'situational',
    desire: '',
  },
  {
    id: 'sit-under-orientation',
    title: 'Orientation anchor',
    body_cue: 'name where you are out loud',
    micro: 'say one landmark',
    container: 'situational',
    category: 'situational',
    desire: '',
  },
  {
    id: 'sit-under-sensation',
    title: 'Sensation spark',
    body_cue: 'smell something vivid and breathe once',
    micro: 'bring scent to nose',
    container: 'situational',
    category: 'situational',
    desire: '',
  },
  {
    id: 'sit-under-permission',
    title: 'Permission anchor',
    body_cue: 'say, “I can start small; that still counts.”',
    micro: 'one nod forward',
    container: 'situational',
    category: 'situational',
    desire: '',
  },

  // Mentally looped (Theme: interrupt spin with physical reference.)
  {
    id: 'sit-loop-touch',
    title: 'Ground touch',
    body_cue: 'hands on thighs or floor; name texture and temperature',
    micro: 'tap fingers once',
    container: 'situational',
    category: 'situational',
    desire: '',
  },
  {
    id: 'sit-loop-reset',
    title: 'Out-loud reset',
    body_cue: 'speak what you’re thinking instead of replaying it',
    micro: 'whisper one word, then exhale',
    container: 'situational',
    category: 'situational',
    desire: '',
  },
  {
    id: 'sit-loop-movement',
    title: 'Movement anchor',
    body_cue: 'walk to another spot; let body lead',
    micro: 'take three steps',
    container: 'situational',
    category: 'situational',
    desire: '',
  },
  {
    id: 'sit-loop-pattern',
    title: 'Visual pattern break',
    body_cue: 'find five objects of the same color',
    micro: 'spot one repeat',
    container: 'situational',
    category: 'situational',
    desire: '',
  },

  // Socially drained (Theme: reclaim personal rhythm after contact.)
  {
    id: 'sit-social-corner',
    title: 'Quiet corner',
    body_cue: 'step away or mute notifications',
    micro: 'turn head aside',
    container: 'situational',
    category: 'situational',
    desire: '',
  },
  {
    id: 'sit-social-skin',
    title: 'Skin boundary',
    body_cue: 'hand over heart or chest; feel pulse',
    micro: 'palm to chest',
    container: 'situational',
    category: 'situational',
    desire: '',
  },
  {
    id: 'sit-social-breath',
    title: 'Reclaim breath',
    body_cue: 'sigh audibly; clear conversation residue',
    micro: 'one low hum',
    container: 'situational',
    category: 'situational',
    desire: '',
  },
  {
    id: 'sit-social-affirmation',
    title: 'Simple affirmation',
    body_cue: '“I’m allowed to be quiet now.”',
    micro: 'whisper it once',
    container: 'situational',
    category: 'situational',
    desire: '',
  },

  // Emotionally flooded (Theme: widen the container, slow the tide.)
  {
    id: 'sit-flood-texture',
    title: 'Texture anchor',
    body_cue: 'hold something cool or rough; focus on feel',
    micro: 'notice texture change',
    container: 'situational',
    category: 'situational',
    desire: '',
  },
  {
    id: 'sit-flood-naming',
    title: 'Naming anchor',
    body_cue: 'quietly label the feeling without story',
    micro: 'say one word',
    container: 'situational',
    category: 'situational',
    desire: '',
  },
  {
    id: 'sit-flood-breath',
    title: 'Containment breath',
    body_cue: 'exhale as if drawing a soft circle around yourself',
    micro: 'slow exhale through pursed lips',
    container: 'situational',
    category: 'situational',
    desire: '',
  },
  {
    id: 'sit-flood-weight',
    title: 'Gentle weight',
    body_cue: 'wrap in blanket or rest hand on chest or thighs',
    micro: 'press palm to thigh',
    container: 'situational',
    category: 'situational',
    desire: '',
  },

  // --- Uplift and Expansion (Category: uplift) ---
  // Energized / Inspired (Theme: channel charge into coherence.)
  {
    id: 'up-inspire-body',
    title: 'Body anchor',
    body_cue: 'notice where energy gathers; give it small movement',
    micro: 'shake or tap once',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },
  {
    id: 'up-inspire-pacing',
    title: 'Breath pacing',
    body_cue: 'longer exhale than inhale; sync with pulse',
    micro: 'one slow exhale',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },
  {
    id: 'up-inspire-containment',
    title: 'Containment check',
    body_cue: 'one breath pause before acting or sharing',
    micro: 'one-count pause',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },
  {
    id: 'up-inspire-integration',
    title: 'Integration mark',
    body_cue: 'capture idea briefly without chasing it',
    micro: 'say or jot one sentence',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },

  // Clear / Focused (Theme: preserve clarity without tightening.)
  {
    id: 'up-clear-vision',
    title: 'Vision softening',
    body_cue: 'look away from screens, focus on something natural',
    micro: 'glance at plant or window',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },
  {
    id: 'up-clear-posture',
    title: 'Posture reminder',
    body_cue: 'lengthen spine, drop shoulders, exhale',
    micro: 'small upward stretch',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },
  {
    id: 'up-clear-sense',
    title: 'Sense check',
    body_cue: 'name one sound and one scent',
    micro: 'identify one sound',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },
  {
    id: 'up-clear-completion',
    title: 'Completion cue',
    body_cue: 'exhale, look around, then stand',
    micro: 'one closing breath',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },

  // Connected / Open (Theme: stay empathetic but differentiated.)
  {
    id: 'up-connect-boundary',
    title: 'Boundary touch',
    body_cue: 'hand on arm or chest while listening',
    micro: 'self-touch once',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },
  {
    id: 'up-connect-sync',
    title: 'Breath sync',
    body_cue: 'match another’s breath briefly, then return to yours',
    micro: 'notice first solo breath',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },
  {
    id: 'up-connect-eye',
    title: 'Eye softening',
    body_cue: 'blink slowly, widen peripheral view',
    micro: 'one slow blink',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },
  {
    id: 'up-connect-afterglow',
    title: 'Afterglow check',
    body_cue: 'ask, “what belongs to me, what belongs to them?”',
    micro: 'whisper “mine / yours.”',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },

  // Creative Flow (Theme: expression without burnout.)
  {
    id: 'up-flow-movement',
    title: 'Movement pulse',
    body_cue: 'sway, stretch, or tap rhythmically',
    micro: 'one body sway',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },
  {
    id: 'up-flow-ground',
    title: 'Mini ground',
    body_cue: 'feel feet or seat; remember body in creation',
    micro: 'press feet once',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },
  {
    id: 'up-flow-pause',
    title: 'Pause-and-scan',
    body_cue: 'ask, “am I still comfortable?”',
    micro: 'roll neck',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },
  {
    id: 'up-flow-closure',
    title: 'Closure cue',
    body_cue: 'close eyes, breathe, thank the work',
    micro: 'hand to heart',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },

  // Expansive / Transcendent (Theme: anchor awe so it integrates.)
  {
    id: 'up-trans-real',
    title: 'Name the real',
    body_cue: 'describe one ordinary thing nearby',
    micro: 'say it quietly',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },
  {
    id: 'up-trans-gesture',
    title: 'Grounding gesture',
    body_cue: 'thumb and middle finger pressed together; feel pulse',
    micro: 'small squeeze',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },
  {
    id: 'up-trans-weight',
    title: 'Weight return',
    body_cue: 'sense gravity; feel support points',
    micro: 'shift weight slightly',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },
  {
    id: 'up-trans-statement',
    title: 'Integration statement',
    body_cue: 'whisper, “This moment can live inside me.”',
    micro: 'repeat silently',
    container: 'uplift',
    category: 'uplift',
    desire: '',
  },
];
