import { Ally, ContainerItem } from './Types';

// Default Chemical Allies
export const DEFAULT_ALLIES: Ally[] = [
  {
    id: 'firestarter',
    name: 'The Firestarter',
    face: '⚙️',
    invocation: 'May this flame light what matters, not what merely demands.',
    function: 'Ignites focus, momentum, motion — reminds the nervous system of possibility.',
    shadow: 'Mistakes speed for progress; burns through rest, not toward it.',
    ritual: 'Before dosing — place one hand on your chest, feel the heartbeat you\'re about to quicken. Whisper: "Burn bright, not away."',
  },
  {
    id: 'mirror',
    name: 'The Mirror and the Mystery',
    face: '🌌',
    invocation: 'Show me myself as cosmos, but bring me back whole.',
    function: 'Expands the membrane between self and all — reveals the divine recursion in experience.',
    shadow: 'Reveals too much too fast — replaces integration with revelation.',
    ritual: 'Before the threshold, speak one truth you\'re willing to lose and one you wish to keep.',
  },
  {
    id: 'chalice',
    name: 'The Hollow Chalice',
    face: '🍷',
    invocation: 'Let this cup open warmth, not emptiness.',
    function: 'Loosens the social heart, dissolves distance, invites song.',
    shadow: 'Hollows the self in the name of connection.',
    ritual: 'Touch your glass to your lips, then pause — breathe once before the sip. Ask: "Am I joining, or escaping?"',
  },
  {
    id: 'tinkerer',
    name: 'The Tinkerer',
    face: '💨',
    invocation: 'Let curiosity spark, not spiral.',
    function: 'Sharpens attention, traces detail, ritualizes pause.',
    shadow: 'Turns precision into obsession; mistake control for safety.',
    ritual: 'Exhale deliberately. Watch the smoke/diffusion fade and whisper: "Release what I tried to fix."',
  },
  {
    id: 'entropy',
    name: 'Entropy\'s Embrace',
    face: '⚫',
    invocation: 'Hold me until I can hold myself.',
    function: 'Teaches surrender, relief, and the grace of rest.',
    shadow: 'Makes oblivion seductive; trades awareness for absence.',
    ritual: 'Before contact — press a hand into the earth, bed, or floor. Feel gravity\'s embrace and say: "May I return."',
  },
  {
    id: 'godmother',
    name: 'The Green Godmother',
    face: '🍃',
    invocation: 'Let me see the pattern without losing form.',
    function: 'Bridges sensory and symbolic worlds — a translator between logic and intuition.',
    shadow: 'Turns awe into apathy; mists clarity under the guise of peace.',
    ritual: 'After inhaling, touch something textured — leaf, fabric, wall — whisper: "Anchor the wonder."',
  },
  {
    id: 'silence',
    name: 'The Mother of Silence',
    face: '🌊',
    invocation: 'Teach me calm that still remembers.',
    function: 'Soothes storms, restores coherence, holds panic like a child.',
    shadow: 'Quiet becomes erasure; calm becomes dependence.',
    ritual: 'After dosing, listen for the quietest sound in your environment — say softly: "I remain."',
  },
  {
    id: 'architect',
    name: 'The Architect',
    face: '🧠',
    invocation: 'May structure serve spirit.',
    function: 'Refines clarity, strengthens connection, rebuilds cognitive architecture.',
    shadow: 'Seeks perfection where presence would suffice.',
    ritual: 'Before swallowing, tap the capsule or cup three times and say: "Alive design, not rigid design."',
  },
];

// Default Grounding Anchors
export const DEFAULT_GROUNDING_ITEMS: ContainerItem[] = [
  // Morning anchors
  {
    id: 'morning-light',
    title: 'Light check-in',
    body_cue: 'notice the quality of light, warm or cool, bright or dim',
    micro: 'lift your eyes toward it',
    type: 'grounding',
    container: 'morning',
    category: 'time',
  },
  {
    id: 'morning-body',
    title: 'Body arrival',
    body_cue: 'sense where weight meets ground; let breath lengthen',
    micro: 'feel your feet',
    type: 'grounding',
    container: 'morning',
    category: 'time',
  },
  {
    id: 'morning-gratitude',
    title: 'First gratitude',
    body_cue: 'name one thing that doesn\'t hurt, confuse, or demand',
    micro: 'whisper "thank you" once',
    type: 'grounding',
    container: 'morning',
    category: 'time',
  },
  {
    id: 'morning-breath',
    title: 'Slow breath',
    body_cue: 'three slow inhales through nose, exhale through mouth',
    micro: 'one conscious breath',
    type: 'grounding',
    container: 'morning',
    category: 'time',
  },
  
  // Afternoon anchors
  {
    id: 'afternoon-hydration',
    title: 'Hydration reset',
    body_cue: 'taste water; track its coolness through the throat',
    micro: 'one sip with attention',
    type: 'grounding',
    container: 'afternoon',
    category: 'time',
  },
  {
    id: 'afternoon-muscle',
    title: 'Muscle check',
    body_cue: 'unclench jaw, roll shoulders, exhale',
    micro: 'drop shoulders once',
    type: 'grounding',
    container: 'afternoon',
    category: 'time',
  },
  {
    id: 'afternoon-horizon',
    title: 'Horizon view',
    body_cue: 'find something distant and rest your eyes there',
    micro: 'glance toward open space',
    type: 'grounding',
    container: 'afternoon',
    category: 'time',
  },
  {
    id: 'afternoon-truth',
    title: 'Truth check',
    body_cue: 'ask silently, "what\'s actually true right now?"',
    micro: 'one honest exhale',
    type: 'grounding',
    container: 'afternoon',
    category: 'time',
  },
  
  // Evening anchors
  {
    id: 'evening-lighting',
    title: 'Lighting shift',
    body_cue: 'lower brightness; let color temperature warm',
    micro: 'dim one lamp',
    type: 'grounding',
    container: 'evening',
    category: 'time',
  },
  {
    id: 'evening-water',
    title: 'Water ritual',
    body_cue: 'wash or rinse hands slowly, feeling texture and change',
    micro: 'wet palms briefly',
    type: 'grounding',
    container: 'evening',
    category: 'time',
  },
  {
    id: 'evening-closure',
    title: 'Small closure',
    body_cue: 'ask "what can I set down now?"',
    micro: 'one slow sigh',
    type: 'grounding',
    container: 'evening',
    category: 'time',
  },
  
  // Late night anchors
  {
    id: 'late-breath',
    title: 'Breath cadence',
    body_cue: 'inhale four, hold two, exhale six',
    micro: 'one conscious breath',
    type: 'grounding',
    container: 'late',
    category: 'time',
  },
  {
    id: 'late-nest',
    title: 'Nest ritual',
    body_cue: 'adjust blanket, find comfort, whisper "safe now"',
    micro: 'smooth pillow once',
    type: 'grounding',
    container: 'late',
    category: 'time',
  },
  {
    id: 'late-release',
    title: 'Final release',
    body_cue: 'scan body; soften one area that feels held',
    micro: 'unclench tongue from roof of mouth',
    type: 'grounding',
    container: 'late',
    category: 'time',
  },
  
  // Situational - Overstimulated
  {
    id: 'sit-temperature',
    title: 'Temperature anchor',
    body_cue: 'run cool water over wrists or back of neck until breath slows',
    micro: 'touch cool surface',
    type: 'grounding',
    container: 'morning',
    category: 'situational',
  },
  {
    id: 'sit-boundary',
    title: 'Boundary anchor',
    body_cue: 'lean back against a wall or solid surface; feel where your edges end',
    micro: 'press one shoulder to wall',
    type: 'grounding',
    container: 'morning',
    category: 'situational',
  },
  {
    id: 'sit-sound',
    title: 'Sound anchor',
    body_cue: 'find a quiet low tone (fan, hum, white noise); match breath to it',
    micro: 'notice silence between sounds',
    type: 'grounding',
    container: 'morning',
    category: 'situational',
  },
  {
    id: 'sit-visual',
    title: 'Visual anchor',
    body_cue: 'lower your gaze; soften focus; let the world blur for a few seconds',
    micro: 'close eyes halfway',
    type: 'grounding',
    container: 'morning',
    category: 'situational',
  },
  
  // Uplift - Energized/Inspired
  {
    id: 'up-body',
    title: 'Body anchor',
    body_cue: 'notice where energy gathers (chest, hands, jaw); give it a small movement',
    micro: 'shake or tap that spot once',
    type: 'grounding',
    container: 'morning',
    category: 'uplift',
  },
  {
    id: 'up-breath',
    title: 'Breath pacing',
    body_cue: 'keep exhale longer than inhale; match rhythm to heartbeat',
    micro: 'one slow exhale',
    type: 'grounding',
    container: 'morning',
    category: 'uplift',
  },
  {
    id: 'up-containment',
    title: 'Containment check',
    body_cue: 'before sharing or acting, pause one breath: "Is this impulse ready or raw?"',
    micro: 'one-count pause before move',
    type: 'grounding',
    container: 'morning',
    category: 'uplift',
  },
  {
    id: 'up-integration',
    title: 'Integration mark',
    body_cue: 'jot or voice a quick note to capture the spark without chasing it',
    micro: 'speak one sentence aloud',
    type: 'grounding',
    container: 'morning',
    category: 'uplift',
  },
];

